In [1]:
import numpy as np

In [32]:
x = np.array(range(1,6))

In [33]:
x

array([1, 2, 3, 4, 5])

# 0-1 Normalization

In [34]:
scaled = (x - x.min()) / (x.max() - x.min())

In [35]:
scaled

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Standardization - Z Score
> Centers at 0, std = 1

In [44]:
x.std()

np.float64(1.4142135623730951)

In [45]:
x.mean()

np.float64(3.0)

In [46]:
z = (x - x.mean()) / x.std()

In [47]:
z

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])